export const placehol = [
  "Telangana",
  "Bombay",
  "Kerala",
  "Gujarat",
  "Hyderabad",
];

export let States = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];
export const Options = {
  // plotOptions: {
  //   pie: {
  //     donut: {
  //       size: "65%",
  //     },
  //   },
  // },
  labels: ["ELEMENTERY", "HIGHSCHOOL", "TECHNICAL"],
  colors: ["#4287f5", "#39eaed", "#9e4ca8"],
  chart: {
    width: 380,
    type: "donut",
  },
  plotOptions: {
    pie: {
      donut: {
        size: "50%",
      },
    },
  },
  dataLabels: {
    enabled: false,
  },
  responsive: [
    {
      breakpoint: 480,
      options: {
        chart: {
          width: 200,
        },
        legend: {
          show: false,
        },
      },
    },
  ],
  legend: {
    position: "right",
    offsetY: 0,
    height: 630,
  },
};

export const StatesXcolor = [
  { State: "an", Color: ["255", "26", "26"] },
  { State: "ap", Color: ["255", "26", "26"] },
  { State: "ar", Color: ["255", "26", "26"] },
  { State: "as", Color: ["255", "26", "26"] },
  { State: "br", Color: ["255", "26", "26"] },
  { State: "ch", Color: ["255", "26", "26"] },
  { State: "ct", Color: ["255", "26", "26"] },
  { State: "dn", Color: ["255", "26", "26"] },
  { State: "dd", Color: ["255", "26", "26"] },
  { State: "dl", Color: ["255", "26", "26"] },
  { State: "ga", Color: ["255", "26", "26"] },
  { State: "gj", Color: ["255", "26", "26"] },
  { State: "hr", Color: ["255", "26", "26"] },
  { State: "hp", Color: ["255", "26", "26"] },
  { State: "jk", Color: ["255", "26", "26"] },
  { State: "jh", Color: ["255", "26", "26"] },
  { State: "ka", Color: ["255", "26", "26"] },
  { State: "kl", Color: ["255", "26", "26"] },
  { State: "ld", Color: ["255", "26", "26"] },
  { State: "mp", Color: ["255", "26", "26"] },
  { State: "mh", Color: ["255", "26", "26"] },
  { State: "mn", Color: ["255", "26", "26"] },
  { State: "ml", Color: ["255", "26", "26"] },
  { State: "mz", Color: ["255", "26", "26"] },
  { State: "nl", Color: ["255", "26", "26"] },
  { State: "or", Color: ["255", "26", "26"] },
  { State: "py", Color: ["255", "26", "26"] },
  { State: "pb", Color: ["255", "26", "26"] },
  { State: "rj", Color: ["255", "26", "26"] },
  { State: "sk", Color: ["255", "26", "26"] },
  { State: "tn", Color: ["255", "26", "26"] },
  { State: "tg", Color: ["255", "26", "26"] },
  { State: "tr", Color: ["255", "26", "26"] },
  { State: "up", Color: ["255", "26", "26"] },
  { State: "ut", Color: ["255", "26", "26"] },
  { State: "wb", Color: ["255", "26", "26"] },
];
